name: ApplicationBuild

on: [push, pull_request]

#まだ動かない
#env:
#  OUTPUT_PATH: "D:/apk"
#  BUNDLE_ID: "com.hoge.hogehoge"
#  PRODUCT_NAME: "New Unity Project"
#  COMPANY_NAME: "DefaultCompany"
#  UNITY_VERSION: 2019.3.3f1

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Android Build
      run: powershell -command "& '${{ secrets.UNITY_EDITOR_PATH }}'" -quit -logFile .\build.log -projectPath ${{ secrets.PROJECT_PATH }} -executeMethod MobileBuild.TestBuild -buildTarget Android
