name: ApplicationBuild

on: [push, pull_request]

env:
  OUTPUT_PATH: "D:\apk"
  BUNDLE_ID: "com.hoge.hogehoge"
  PRODUCT_NAME: "New Unity Project"
  COMPANY_NAME: "DefaultCompany"
  UNITY_VERSION: 2019.3.3f1
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Android Build
      run: C:\ProgramFiles\Unity\Hub\Editor\2019.3.3f1\Editor\Unity.exe -quit -batchmode -nographics -silent-crashes -logFile \
          -projectPath ./ -executeMethod MobileBuild.BuildAndroid -buildTarget Android
